//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assign
    {
        public int AssignId { get; set; }
        public Nullable<int> AssignCode { get; set; }
        public int TicketID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<int> AssignZoneId { get; set; }
        public Nullable<int> ZoneCode { get; set; }
        public string ZoneDetails { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactNo { get; set; }
        public string CustomerAddress { get; set; }
        public string ProductName { get; set; }
        public string ProblemName { get; set; }
        public string fsp { get; set; }
        public string pmodel { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public string OtherReceiver { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsAssign { get; set; }
        public Nullable<bool> SendFeedback { get; set; }
        public Nullable<bool> SendGate { get; set; }
        public string PSMode { get; set; }
        public string PSNote { get; set; }
        public Nullable<int> PsScId { get; set; }
        public string PsApplyBy { get; set; }
        public Nullable<System.DateTime> PsApplyDate { get; set; }
        public string Ps1stApv { get; set; }
        public Nullable<System.DateTime> Ps1stAppDate { get; set; }
        public string PsDistRecv { get; set; }
        public Nullable<System.DateTime> PsDistRecvDate { get; set; }
        public string PsRejCoz { get; set; }
        public string SmsBody { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string SRInfo { get; set; }
        public string SRNumber { get; set; }
        public string SRMode { get; set; }
        public string SRrejectCause { get; set; }
        public Nullable<int> SrScId { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string SrImage1 { get; set; }
        public string SrImage2 { get; set; }
        public string SrApplyBy { get; set; }
        public Nullable<System.DateTime> SrApplyDate { get; set; }
        public string Sr1stApv { get; set; }
        public Nullable<System.DateTime> Sr1stApvDate { get; set; }
        public string SrFinalApv { get; set; }
        public Nullable<System.DateTime> SrFinalApvDate { get; set; }
        public Nullable<System.DateTime> SrNoInDate { get; set; }
        public string SrComment { get; set; }
        public string SrDP { get; set; }
        public string SrFinalComment { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string BillNote { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillFlag { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Discount { get; set; }
    }
}
