//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int TicketID { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public Nullable<int> SalesInvoiceId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerFatherName { get; set; }
        public string ContactNo { get; set; }
        public string AlternativeContactNo { get; set; }
        public string Location { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string ProSerialNo { get; set; }
        public Nullable<int> problemId { get; set; }
        public string ProblemName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> apid { get; set; }
        public string Assigned { get; set; }
        public Nullable<bool> SendAssign { get; set; }
        public string fsp { get; set; }
        public string pmodel { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
