//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoReturnLog
    {
        public int DepoReturnID { get; set; }
        public string DeporeturnBarcode { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string DealerAddress { get; set; }
        public string DealearTruckNumber { get; set; }
        public Nullable<int> DepoID { get; set; }
        public string DepoName { get; set; }
        public string Entryby { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
