//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoToDepoLogFileWeight
    {
        public int DepoLogID { get; set; }
        public string BarcodeNo { get; set; }
        public int FromDepoID { get; set; }
        public int ToDepoID { get; set; }
        public string SentBy { get; set; }
        public System.DateTime SentDate { get; set; }
        public string EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
