//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionEntryInfo
    {
        public int DistId { get; set; }
        public int ComplainNo { get; set; }
        public int SerialNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public Nullable<int> SCId { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> DillerCode { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> EngineerId { get; set; }
        public string EngineerName { get; set; }
        public Nullable<int> EngrStaffID { get; set; }
        public string EngrContactNo { get; set; }
        public string EngrEmail { get; set; }
        public int ProductId { get; set; }
        public int PrModelId { get; set; }
        public Nullable<int> ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<int> DistDurationTime { get; set; }
        public Nullable<bool> SendService { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ReceivePerson { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
