//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionWeight
    {
        public long ThaDstbId { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ModelCode { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> FgDvId { get; set; }
        public string TName { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public Nullable<int> DepotId { get; set; }
        public string DepotName { get; set; }
        public Nullable<int> MoRcvTyId { get; set; }
        public string RcvTName { get; set; }
        public Nullable<int> FcLocId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> DepoLocId { get; set; }
        public string DepoLocName { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<bool> IsReceive { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<bool> IsTO { get; set; }
        public string OCNo { get; set; }
        public string OCSender { get; set; }
        public Nullable<System.DateTime> OCSendDate { get; set; }
        public Nullable<bool> TruckLoad { get; set; }
        public string DepoRemarks { get; set; }
        public string DepoOutRemarks { get; set; }
        public string Position { get; set; }
        public string SRRecv { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<System.DateTime> PGDate { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string Username { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> DeliveryTypeID { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> TodepoID { get; set; }
        public string ToDepoName { get; set; }
        public Nullable<System.DateTime> DepoReturnDate { get; set; }
        public string DepoReturnRemReason { get; set; }
        public string DealerAddress { get; set; }
        public string DeliveryType { get; set; }
    }
}
