//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public int TicketID { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public string FeedBackInfo { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> problemId { get; set; }
        public Nullable<int> ActualProblemId { get; set; }
        public string SolvedBy { get; set; }
        public Nullable<int> SolvedByStaffId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string SerialNo { get; set; }
        public string UsedSpareParts { get; set; }
        public Nullable<decimal> ServiceChargeOW { get; set; }
        public Nullable<int> WarCardNo { get; set; }
        public string MoneyReceiptNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string SRInfo { get; set; }
        public string SRNumber { get; set; }
        public string SRMode { get; set; }
        public string SRrejectCause { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
