//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldComplain
    {
        public int TId { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<int> ModelQty { get; set; }
        public string GsModel { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> NfId { get; set; }
        public Nullable<int> AcId { get; set; }
        public Nullable<int> PartsId { get; set; }
        public Nullable<int> PQty { get; set; }
        public Nullable<int> SpartsId { get; set; }
        public Nullable<int> SQty { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Warrenty { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<int> Mc { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> CfNo { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> MoneyRecNo { get; set; }
        public string WarCardNo { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> BaseId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remarks { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string ExtraPartCost { get; set; }
    }
}
