//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlytechnicianFeedbackExcel
    {
        public int MonthlyFeedbackID { get; set; }
        public int TicketID { get; set; }
        public System.DateTime AttendDate { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public int ItemCode { get; set; }
        public string ZoneName { get; set; }
        public int StaffID { get; set; }
        public string ProductName { get; set; }
        public string PrModelName { get; set; }
        public string ProblemName { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
    }
}
