//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherCost
    {
        public long OTrId { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public Nullable<int> SCId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> OId { get; set; }
        public Nullable<int> OQty { get; set; }
        public Nullable<decimal> ORate { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
