//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QcMaster
    {
        public int MId { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string PrModelName { get; set; }
        public string QcInfo { get; set; }
        public Nullable<int> Qty { get; set; }
        public string IsProb { get; set; }
        public Nullable<int> CurSteps { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
