//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RMILCSDbEntities : DbContext
    {
        public RMILCSDbEntities()
            : base("name=RMILCSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionTaken> ActionTaken { get; set; }
        public DbSet<Assign> Assign { get; set; }
        public DbSet<BaseEngr> BaseEngr { get; set; }
        public DbSet<Boring> Boring { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Complain> Complain { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<DamageReturnInfo> DamageReturnInfo { get; set; }
        public DbSet<DealerDetails> DealerDetails { get; set; }
        public DbSet<DemageReturnCost> DemageReturnCost { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<DepoReturnLog> DepoReturnLog { get; set; }
        public DbSet<DepotWeight> DepotWeight { get; set; }
        public DbSet<DepoWiseUserAssign> DepoWiseUserAssign { get; set; }
        public DbSet<Designation> Designation { get; set; }
        public DbSet<Diller> Diller { get; set; }
        public DbSet<DistributionDeliveryType> DistributionDeliveryType { get; set; }
        public DbSet<DistributionEntryInfo> DistributionEntryInfo { get; set; }
        public DbSet<DistributionWeight> DistributionWeight { get; set; }
        public DbSet<DN> DN { get; set; }
        public DbSet<Engineer> Engineer { get; set; }
        public DbSet<FCompany> FCompany { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<FieldAction> FieldAction { get; set; }
        public DbSet<FieldComplain> FieldComplain { get; set; }
        public DbSet<FieldParts> FieldParts { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<JobCardInfo> JobCardInfo { get; set; }
        public DbSet<Mail_Information> Mail_Information { get; set; }
        public DbSet<MasterBoxAssigned> MasterBoxAssigned { get; set; }
        public DbSet<Menus> Menus { get; set; }
        public DbSet<MonthCalc> MonthCalc { get; set; }
        public DbSet<MonthlytechnicianFeedbackExcel> MonthlytechnicianFeedbackExcel { get; set; }
        public DbSet<NatureOfFault> NatureOfFault { get; set; }
        public DbSet<NatureOfProblem> NatureOfProblem { get; set; }
        public DbSet<OtherCost> OtherCost { get; set; }
        public DbSet<ParentMenus> ParentMenus { get; set; }
        public DbSet<PartsInfo> PartsInfo { get; set; }
        public DbSet<ProdTarget> ProdTarget { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductionLine> ProductionLine { get; set; }
        public DbSet<ProductModel> ProductModel { get; set; }
        public DbSet<ProdWiseAction> ProdWiseAction { get; set; }
        public DbSet<ProdWiseParts> ProdWiseParts { get; set; }
        public DbSet<ProdWiseProblem> ProdWiseProblem { get; set; }
        public DbSet<PumpParameter> PumpParameter { get; set; }
        public DbSet<QcDetails> QcDetails { get; set; }
        public DbSet<QcMaster> QcMaster { get; set; }
        public DbSet<QcMove> QcMove { get; set; }
        public DbSet<QcPoint> QcPoint { get; set; }
        public DbSet<QcPointAsn> QcPointAsn { get; set; }
        public DbSet<QcStep> QcStep { get; set; }
        public DbSet<QcSwitch> QcSwitch { get; set; }
        public DbSet<QcUserWiseStep> QcUserWiseStep { get; set; }
        public DbSet<Reference> Reference { get; set; }
        public DbSet<RmilBoxDetails> RmilBoxDetails { get; set; }
        public DbSet<RmilBoxMaster> RmilBoxMaster { get; set; }
        public DbSet<RmilProdDetails> RmilProdDetails { get; set; }
        public DbSet<RmilProdMaster> RmilProdMaster { get; set; }
        public DbSet<RmilUserWiseLinePer> RmilUserWiseLinePer { get; set; }
        public DbSet<SecurityEntryInfo> SecurityEntryInfo { get; set; }
        public DbSet<ServiceCenter> ServiceCenter { get; set; }
        public DbSet<ServiceCenterEntryInfo> ServiceCenterEntryInfo { get; set; }
        public DbSet<ServiceEntryCancelReason> ServiceEntryCancelReason { get; set; }
        public DbSet<SMSBODY> SMSBODY { get; set; }
        public DbSet<SparePartsCost> SparePartsCost { get; set; }
        public DbSet<SparePartsInfo> SparePartsInfo { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<tblCharge> tblCharge { get; set; }
        public DbSet<tblModelPartsRate> tblModelPartsRate { get; set; }
        public DbSet<tblOther> tblOther { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserType> UserType { get; set; }
        public DbSet<UserWiseMenuPer> UserWiseMenuPer { get; set; }
        public DbSet<UserWiseSrPer> UserWiseSrPer { get; set; }
        public DbSet<UseSparePartsCostingInfo> UseSparePartsCostingInfo { get; set; }
        public DbSet<VoltType> VoltType { get; set; }
        public DbSet<WarrantyInfo> WarrantyInfo { get; set; }
        public DbSet<Zone> Zone { get; set; }
        public DbSet<DistributionWeight6226> DistributionWeight6226 { get; set; }
        public DbSet<MasterBoxAssigned6226> MasterBoxAssigned6226 { get; set; }
        public DbSet<RptCosting> RptCosting { get; set; }
        public DbSet<RptCostingDetails> RptCostingDetails { get; set; }
        public DbSet<vw_AllSearchFromAssign> vw_AllSearchFromAssign { get; set; }
        public DbSet<vw_AssignbySmsBody1> vw_AssignbySmsBody1 { get; set; }
        public DbSet<vw_AssignDataZoneWise> vw_AssignDataZoneWise { get; set; }
        public DbSet<vw_AssignList> vw_AssignList { get; set; }
        public DbSet<vw_AssignListForPs> vw_AssignListForPs { get; set; }
        public DbSet<vw_AssignListZoneWise> vw_AssignListZoneWise { get; set; }
        public DbSet<vw_AssignListZoneWiseWithTechnician> vw_AssignListZoneWiseWithTechnician { get; set; }
        public DbSet<vw_AutoAsnDataZoneWise> vw_AutoAsnDataZoneWise { get; set; }
        public DbSet<vw_BaseEnrList> vw_BaseEnrList { get; set; }
        public DbSet<vw_CategoryList> vw_CategoryList { get; set; }
        public DbSet<vw_ChargeList> vw_ChargeList { get; set; }
        public DbSet<vw_Costing> vw_Costing { get; set; }
        public DbSet<vw_DealerDepotDetails> vw_DealerDepotDetails { get; set; }
        public DbSet<vw_DemageReturnCostingList> vw_DemageReturnCostingList { get; set; }
        public DbSet<vw_DepoWiseUserAssign> vw_DepoWiseUserAssign { get; set; }
        public DbSet<vw_DistributionDetails> vw_DistributionDetails { get; set; }
        public DbSet<vw_DistributionDetailsV> vw_DistributionDetailsV { get; set; }
        public DbSet<vw_DistributionDetailsVV> vw_DistributionDetailsVV { get; set; }
        public DbSet<vw_DistributionDetailsVVV> vw_DistributionDetailsVVV { get; set; }
        public DbSet<vw_DistributionDetailsVVVV> vw_DistributionDetailsVVVV { get; set; }
        public DbSet<vw_DistributionEntryList> vw_DistributionEntryList { get; set; }
        public DbSet<vw_DRCost> vw_DRCost { get; set; }
        public DbSet<vw_DRSubTotal> vw_DRSubTotal { get; set; }
        public DbSet<vw_EngrList> vw_EngrList { get; set; }
        public DbSet<vw_FieldComList> vw_FieldComList { get; set; }
        public DbSet<vw_FieldServicingReport> vw_FieldServicingReport { get; set; }
        public DbSet<vw_GetbillinfoByDate> vw_GetbillinfoByDate { get; set; }
        public DbSet<vw_GlobalSearchFromAssign> vw_GlobalSearchFromAssign { get; set; }
        public DbSet<vw_JobCardList> vw_JobCardList { get; set; }
        public DbSet<vw_LineWDailyTargetList> vw_LineWDailyTargetList { get; set; }
        public DbSet<vw_MasterBoxDetails> vw_MasterBoxDetails { get; set; }
        public DbSet<vw_MasterBoxDetailsV> vw_MasterBoxDetailsV { get; set; }
        public DbSet<vw_MasterBoxDetailsVV> vw_MasterBoxDetailsVV { get; set; }
        public DbSet<vw_MenuList> vw_MenuList { get; set; }
        public DbSet<vw_ModelPartsList> vw_ModelPartsList { get; set; }
        public DbSet<vw_ModelWiseSparePartsList> vw_ModelWiseSparePartsList { get; set; }
        public DbSet<vw_OtherCost> vw_OtherCost { get; set; }
        public DbSet<vw_OtherCostingList> vw_OtherCostingList { get; set; }
        public DbSet<vw_OtherSubTotal> vw_OtherSubTotal { get; set; }
        public DbSet<vw_OWCost> vw_OWCost { get; set; }
        public DbSet<vw_PartsCost> vw_PartsCost { get; set; }
        public DbSet<vw_PartsList> vw_PartsList { get; set; }
        public DbSet<vw_PartsSubTotal> vw_PartsSubTotal { get; set; }
        public DbSet<vw_PendingComplain> vw_PendingComplain { get; set; }
        public DbSet<vw_PendingComplainNEW> vw_PendingComplainNEW { get; set; }
        public DbSet<vw_PendingComplainNEWV> vw_PendingComplainNEWV { get; set; }
        public DbSet<vw_PendingComplainNEWVV> vw_PendingComplainNEWVV { get; set; }
        public DbSet<vw_PendingComplainNEWVVV> vw_PendingComplainNEWVVV { get; set; }
        public DbSet<vw_PendingComplainNEWVVVV> vw_PendingComplainNEWVVVV { get; set; }
        public DbSet<vw_PendingComplainNEWVVVVV> vw_PendingComplainNEWVVVVV { get; set; }
        public DbSet<vw_ProdDetails> vw_ProdDetails { get; set; }
        public DbSet<vw_ProductList> vw_ProductList { get; set; }
        public DbSet<vw_ProductModelList> vw_ProductModelList { get; set; }
        public DbSet<vw_ProductWiseActionList> vw_ProductWiseActionList { get; set; }
        public DbSet<vw_ProductWisePartsList> vw_ProductWisePartsList { get; set; }
        public DbSet<vw_ProductWiseProblemList> vw_ProductWiseProblemList { get; set; }
        public DbSet<vw_ProdWiseActAssign> vw_ProdWiseActAssign { get; set; }
        public DbSet<vw_ProdWiseProbAssign> vw_ProdWiseProbAssign { get; set; }
        public DbSet<vw_PsList> vw_PsList { get; set; }
        public DbSet<vw_PumpSelParList> vw_PumpSelParList { get; set; }
        public DbSet<vw_QcExistList> vw_QcExistList { get; set; }
        public DbSet<vw_QcHistDetails> vw_QcHistDetails { get; set; }
        public DbSet<vw_QcHistoryDetails> vw_QcHistoryDetails { get; set; }
        public DbSet<vw_QcMoveList> vw_QcMoveList { get; set; }
        public DbSet<vw_QcPerList> vw_QcPerList { get; set; }
        public DbSet<vw_QcStepsList> vw_QcStepsList { get; set; }
        public DbSet<vw_QcSwitchList> vw_QcSwitchList { get; set; }
        public DbSet<vw_ReferenceList> vw_ReferenceList { get; set; }
        public DbSet<vw_RmBarProdInfo> vw_RmBarProdInfo { get; set; }
        public DbSet<vw_RmilBoxDetails> vw_RmilBoxDetails { get; set; }
        public DbSet<vw_RmilBoxDetailsV> vw_RmilBoxDetailsV { get; set; }
        public DbSet<vw_RmilProdBarCode> vw_RmilProdBarCode { get; set; }
        public DbSet<vw_RptCostingWithProfitLoss> vw_RptCostingWithProfitLoss { get; set; }
        public DbSet<vw_RPTGetCostingDetails> vw_RPTGetCostingDetails { get; set; }
        public DbSet<vw_RPTRevenueDetails> vw_RPTRevenueDetails { get; set; }
        public DbSet<vw_SalesReturnList> vw_SalesReturnList { get; set; }
        public DbSet<vw_SearchFromAssign> vw_SearchFromAssign { get; set; }
        public DbSet<vw_SecurityEntryList> vw_SecurityEntryList { get; set; }
        public DbSet<vw_ServiceCenterStatusCount> vw_ServiceCenterStatusCount { get; set; }
        public DbSet<vw_ServiceCenterStatusPtg> vw_ServiceCenterStatusPtg { get; set; }
        public DbSet<vw_ServiceCostingReport> vw_ServiceCostingReport { get; set; }
        public DbSet<vw_ServiceCostingReportWithProfitLoss> vw_ServiceCostingReportWithProfitLoss { get; set; }
        public DbSet<vw_ServiceCostPrint> vw_ServiceCostPrint { get; set; }
        public DbSet<vw_ServiceList> vw_ServiceList { get; set; }
        public DbSet<vw_ServiceList1> vw_ServiceList1 { get; set; }
        public DbSet<vw_ServicingReport> vw_ServicingReport { get; set; }
        public DbSet<vw_ServicingReportNew> vw_ServicingReportNew { get; set; }
        public DbSet<vw_SparePartsCostingList> vw_SparePartsCostingList { get; set; }
        public DbSet<vw_SparePartsList> vw_SparePartsList { get; set; }
        public DbSet<vw_spList> vw_spList { get; set; }
        public DbSet<vw_SrAppliedList> vw_SrAppliedList { get; set; }
        public DbSet<vw_SrCompleteList> vw_SrCompleteList { get; set; }
        public DbSet<vw_SrFinishList> vw_SrFinishList { get; set; }
        public DbSet<vw_SrSearchList> vw_SrSearchList { get; set; }
        public DbSet<vw_StatusCalcPtg> vw_StatusCalcPtg { get; set; }
        public DbSet<vw_StWisePointAsnList> vw_StWisePointAsnList { get; set; }
        public DbSet<vw_TempSpList> vw_TempSpList { get; set; }
        public DbSet<vw_UpdateAsnDataZoneWise> vw_UpdateAsnDataZoneWise { get; set; }
        public DbSet<vw_UserList> vw_UserList { get; set; }
        public DbSet<vw_UserWiseLineList> vw_UserWiseLineList { get; set; }
        public DbSet<vw_WarrantyInfoList> vw_WarrantyInfoList { get; set; }
        public DbSet<vw_RmilProductDistributionInfo> vw_RmilProductDistributionInfo { get; set; }
        public DbSet<vw_ProductDistributionHistory> vw_ProductDistributionHistory { get; set; }
        public DbSet<vw_ProductDistributionHistoryV> vw_ProductDistributionHistoryV { get; set; }
        public DbSet<VW_ProductModelBarcodeDetails> VW_ProductModelBarcodeDetails { get; set; }
        public DbSet<VW_RmilProductBarcodeDetails> VW_RmilProductBarcodeDetails { get; set; }
        public DbSet<DepoToDepoLogFileWeight> DepoToDepoLogFileWeight { get; set; }
    
        [EdmFunction("RMILCSDbEntities", "sayedtvf")]
        public virtual IQueryable<sayedtvf_Result> sayedtvf(Nullable<int> complainNo)
        {
            var complainNoParameter = complainNo.HasValue ?
                new ObjectParameter("ComplainNo", complainNo) :
                new ObjectParameter("ComplainNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sayedtvf_Result>("[RMILCSDbEntities].[sayedtvf](@ComplainNo)", complainNoParameter);
        }
    
        public virtual ObjectResult<GetCostingDetails1_Result> GetCostingDetails1(Nullable<int> complainNo)
        {
            var complainNoParameter = complainNo.HasValue ?
                new ObjectParameter("ComplainNo", complainNo) :
                new ObjectParameter("ComplainNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCostingDetails1_Result>("GetCostingDetails1", complainNoParameter);
        }
    
        public virtual ObjectResult<GetUnprintedRmilProdMaster_CurrentMonth_Result> GetUnprintedRmilProdMaster_CurrentMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnprintedRmilProdMaster_CurrentMonth_Result>("GetUnprintedRmilProdMaster_CurrentMonth");
        }
    
        public virtual int InsertFieldComplainData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertFieldComplainData");
        }
    
        public virtual ObjectResult<prc_MenuListByUser_Result> prc_MenuListByUser(string userId, Nullable<int> parentMenuId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var parentMenuIdParameter = parentMenuId.HasValue ?
                new ObjectParameter("ParentMenuId", parentMenuId) :
                new ObjectParameter("ParentMenuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_MenuListByUser_Result>("prc_MenuListByUser", userIdParameter, parentMenuIdParameter);
        }
    
        public virtual ObjectResult<prc_SrFinalApvPendingList_Result> prc_SrFinalApvPendingList(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_SrFinalApvPendingList_Result>("prc_SrFinalApvPendingList", userIdParameter);
        }
    
        public virtual ObjectResult<prc_SrFinalApvPendingListByTicketId_Result> prc_SrFinalApvPendingListByTicketId(string userId, Nullable<int> ticketID)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var ticketIDParameter = ticketID.HasValue ?
                new ObjectParameter("TicketID", ticketID) :
                new ObjectParameter("TicketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_SrFinalApvPendingListByTicketId_Result>("prc_SrFinalApvPendingListByTicketId", userIdParameter, ticketIDParameter);
        }
    
        public virtual ObjectResult<prc_SrFirstApvList_Result> prc_SrFirstApvList(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_SrFirstApvList_Result>("prc_SrFirstApvList", userIdParameter);
        }
    
        public virtual ObjectResult<prc_SrFirstApvListByTicketId_Result> prc_SrFirstApvListByTicketId(string userId, Nullable<int> ticketID)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var ticketIDParameter = ticketID.HasValue ?
                new ObjectParameter("TicketID", ticketID) :
                new ObjectParameter("TicketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_SrFirstApvListByTicketId_Result>("prc_SrFirstApvListByTicketId", userIdParameter, ticketIDParameter);
        }
    
        public virtual ObjectResult<RPT_SpGetCostingByTicketId_Result> RPT_SpGetCostingByTicketId(Nullable<int> complainNo)
        {
            var complainNoParameter = complainNo.HasValue ?
                new ObjectParameter("ComplainNo", complainNo) :
                new ObjectParameter("ComplainNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_SpGetCostingByTicketId_Result>("RPT_SpGetCostingByTicketId", complainNoParameter);
        }
    
        public virtual int SearchAssignByTicketID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchAssignByTicketID");
        }
    
        public virtual int sp_DeleteUserWiseMenuPer(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUserWiseMenuPer", userIdParameter);
        }
    
        public virtual ObjectResult<sp_FieldServicingReportProductWise_Result> sp_FieldServicingReportProductWise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FieldServicingReportProductWise_Result>("sp_FieldServicingReportProductWise");
        }
    
        public virtual ObjectResult<sp_FieldServicingReportProductWiseBillInfo_Result> sp_FieldServicingReportProductWiseBillInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FieldServicingReportProductWiseBillInfo_Result>("sp_FieldServicingReportProductWiseBillInfo");
        }
    
        public virtual ObjectResult<sp_GetMonthlyTechnicianFeedbackExcel_Result> sp_GetMonthlyTechnicianFeedbackExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMonthlyTechnicianFeedbackExcel_Result>("sp_GetMonthlyTechnicianFeedbackExcel");
        }
    
        public virtual ObjectResult<sp_GetProductionByShiftDay_Result> sp_GetProductionByShiftDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProductionByShiftDay_Result>("sp_GetProductionByShiftDay");
        }
    
        public virtual ObjectResult<sp_GetProductionByShiftNight_Result> sp_GetProductionByShiftNight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProductionByShiftNight_Result>("sp_GetProductionByShiftNight");
        }
    
        public virtual ObjectResult<sp_GetTopProblemByProductAndDate_Result> sp_GetTopProblemByProductAndDate(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string productName)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTopProblemByProductAndDate_Result>("sp_GetTopProblemByProductAndDate", startDateParameter, endDateParameter, productNameParameter);
        }
    
        public virtual int sp_InsertAssignData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertAssignData");
        }
    
        public virtual int sp_InsertMonthlyTechnicianFeedbackExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertMonthlyTechnicianFeedbackExcel");
        }
    
        public virtual int sp_ProductIdUpdateForSr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProductIdUpdateForSr");
        }
    
        public virtual int SP_ResetDistributionWeight(string barcodeNo)
        {
            var barcodeNoParameter = barcodeNo != null ?
                new ObjectParameter("BarcodeNo", barcodeNo) :
                new ObjectParameter("BarcodeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ResetDistributionWeight", barcodeNoParameter);
        }
    
        public virtual int SP_ResetDistributionWeightV(string barcodeNo)
        {
            var barcodeNoParameter = barcodeNo != null ?
                new ObjectParameter("BarcodeNo", barcodeNo) :
                new ObjectParameter("BarcodeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ResetDistributionWeightV", barcodeNoParameter);
        }
    
        public virtual int sp_RmilDataInsert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RmilDataInsert");
        }
    
        public virtual ObjectResult<sp_RmilProd_Result> sp_RmilProd(Nullable<System.DateTime> entryDate)
        {
            var entryDateParameter = entryDate.HasValue ?
                new ObjectParameter("EntryDate", entryDate) :
                new ObjectParameter("EntryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RmilProd_Result>("sp_RmilProd", entryDateParameter);
        }
    
        public virtual ObjectResult<sp_SelectMonthlyTechnicianFeedbackExcel_Result> sp_SelectMonthlyTechnicianFeedbackExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectMonthlyTechnicianFeedbackExcel_Result>("sp_SelectMonthlyTechnicianFeedbackExcel");
        }
    
        public virtual int sp_SmsDataUpdateToAssign()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SmsDataUpdateToAssign");
        }
    
        public virtual ObjectResult<Sp_TechnicialFeedbackMonthly_Result> Sp_TechnicialFeedbackMonthly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TechnicialFeedbackMonthly_Result>("Sp_TechnicialFeedbackMonthly");
        }
    
        public virtual ObjectResult<spGetCostingDetails_Result> spGetCostingDetails(Nullable<int> complainNo)
        {
            var complainNoParameter = complainNo.HasValue ?
                new ObjectParameter("ComplainNo", complainNo) :
                new ObjectParameter("ComplainNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCostingDetails_Result>("spGetCostingDetails", complainNoParameter);
        }
    
        public virtual ObjectResult<usp_GetUnprintedRmPmLast7Days_Result> usp_GetUnprintedRmPmLast7Days()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUnprintedRmPmLast7Days_Result>("usp_GetUnprintedRmPmLast7Days");
        }
    
        public virtual ObjectResult<sp_GetDistributionProductionDayShift_Result> sp_GetDistributionProductionDayShift()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDistributionProductionDayShift_Result>("sp_GetDistributionProductionDayShift");
        }
    
        public virtual ObjectResult<sp_GetDistributionProductionNightShift_Result> sp_GetDistributionProductionNightShift()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDistributionProductionNightShift_Result>("sp_GetDistributionProductionNightShift");
        }
    }
}
