//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmilProdDetails
    {
        public long RmPdId { get; set; }
        public Nullable<long> RmPmId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> Wpfs { get; set; }
        public string DBarcode { get; set; }
        public Nullable<System.DateTime> MfDate { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<System.DateTime> MfWarDate { get; set; }
        public Nullable<System.DateTime> ServiceWarDate { get; set; }
        public Nullable<System.DateTime> AfterSalesWarrDate { get; set; }
        public Nullable<System.DateTime> AfterSalesServiceDate { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public string CustContactNo { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public Nullable<bool> SendMsg { get; set; }
        public Nullable<int> ServiceNo { get; set; }
        public Nullable<bool> InByForm { get; set; }
        public Nullable<bool> Recharge { get; set; }
        public Nullable<int> TechStaffID { get; set; }
        public string DistStaffID { get; set; }
        public string SenderContact { get; set; }
        public Nullable<bool> Others { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public Nullable<int> BarcodeSent { get; set; }
    }
}
