//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityEntryInfo
    {
        public int TicketID { get; set; }
        public int SerialNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> SCId { get; set; }
        public int ProductId { get; set; }
        public string InTimeVehicleNo { get; set; }
        public string OutTimeVehicleNo { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<int> TotalDurationTime { get; set; }
        public Nullable<bool> SendDist { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
