//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenter
    {
        public int SCId { get; set; }
        public string SCName { get; set; }
        public string DICName { get; set; }
        public string DICEmail { get; set; }
        public string SICName { get; set; }
        public string SICEmail { get; set; }
        public string ICName { get; set; }
        public string ICEmail { get; set; }
        public string AEName { get; set; }
        public string AEEmail { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
