//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenterEntryInfo
    {
        public int Tr_Id { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public int SerialNo { get; set; }
        public Nullable<int> SCId { get; set; }
        public int problemId { get; set; }
        public int ActionId { get; set; }
        public Nullable<int> ActionQty { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> ServiceChargeOW { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string ByFinishWork { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string TestReportInfo { get; set; }
        public string Remarks { get; set; }
        public string SRInfo { get; set; }
        public string SRNumber { get; set; }
        public string SRMode { get; set; }
        public string SRrejectCause { get; set; }
        public Nullable<int> DillerCode { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<int> ServiceDurationTime { get; set; }
        public Nullable<bool> SendCost { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string ModelSerialNo { get; set; }
        public string DeliveryAddress { get; set; }
        public string BillNumber { get; set; }
        public string Billamount { get; set; }
        public string CancelReason { get; set; }
    }
}
