//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSBODY
    {
        public int ID { get; set; }
        public string MSGBODY { get; set; }
        public double MSGID { get; set; }
        public string SENDER { get; set; }
        public string SENTTIME { get; set; }
        public System.DateTime INDATE { get; set; }
    }
}
