//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModelPartsRate
    {
        public int rId { get; set; }
        public int PrModelId { get; set; }
        public int SparePartsId { get; set; }
        public decimal UnitRate { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
