//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AssignDataZoneWise
    {
        public int AssignId { get; set; }
        public int TicketID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<int> AssignZoneId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContactNo { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string ProductName { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsAssign { get; set; }
        public Nullable<bool> SendFeedback { get; set; }
        public Nullable<bool> SendGate { get; set; }
        public string SmsBody { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string StatusName { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> ComplainDate { get; set; }
        public string ProblemName { get; set; }
        public string SenderName { get; set; }
    }
}
