//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllSearchFromAssign
    {
        public int TicketID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactNo { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProblemName { get; set; }
        public string StatusName { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string PrModelName { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string fsp { get; set; }
        public Nullable<bool> IsAssign { get; set; }
        public Nullable<bool> SendFeedback { get; set; }
        public Nullable<bool> SendGate { get; set; }
        public string SRInfo { get; set; }
        public string SRNumber { get; set; }
        public string SRrejectCause { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string SrApplyBy { get; set; }
        public Nullable<System.DateTime> SrApplyDate { get; set; }
        public string Sr1stApv { get; set; }
        public Nullable<System.DateTime> Sr1stApvDate { get; set; }
        public string SrFinalApv { get; set; }
        public Nullable<System.DateTime> SrFinalApvDate { get; set; }
        public Nullable<System.DateTime> SrNoInDate { get; set; }
        public string SrComment { get; set; }
        public string SrDP { get; set; }
        public string SrFinalComment { get; set; }
        public Nullable<int> SrScId { get; set; }
        public string SCName { get; set; }
        public string Sr1stApvId { get; set; }
        public string SrFinalApvId { get; set; }
        public string SrApplyId { get; set; }
        public string Remarks { get; set; }
        public string SRMode { get; set; }
        public string SMode { get; set; }
    }
}
