//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BaseEnrList
    {
        public int BaseId { get; set; }
        public string BaseName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
    }
}
