//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Costing
    {
        public int ComplainNo { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> SparePartsId { get; set; }
        public string SparePartsName { get; set; }
        public Nullable<int> SQty { get; set; }
        public Nullable<decimal> SRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> OId { get; set; }
        public string Name { get; set; }
        public Nullable<int> OQty { get; set; }
        public Nullable<decimal> ORate { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<int> Dr_Id { get; set; }
        public string DamagePartsName { get; set; }
        public Nullable<decimal> DQty { get; set; }
        public Nullable<decimal> DRate { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
    }
}
