//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DistributionDetailsV
    {
        public long ThaDstbId { get; set; }
        public string BoxBarCode { get; set; }
        public string BarcodeNo { get; set; }
        public string ProductName { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public string DealerAddress { get; set; }
        public string VehicleNumber { get; set; }
        public string DepotName { get; set; }
        public string ToDepoName { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public int DeliveryTypeID { get; set; }
        public string DeliveryTypeName { get; set; }
    }
}
