//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DealerDepotDetails
    {
        public int Dlid { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> DzId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string Password { get; set; }
        public string trucknumber { get; set; }
        public Nullable<int> DepoID { get; set; }
        public string DepotName { get; set; }
    }
}
