//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JobCardList
    {
        public int JobID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ProblemId { get; set; }
        public string ProblemName { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionName { get; set; }
        public string SpareParts { get; set; }
        public Nullable<decimal> WireSize { get; set; }
        public Nullable<decimal> TotWireWeight { get; set; }
        public string CDNo { get; set; }
        public string Technician { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> SCId { get; set; }
        public string SCName { get; set; }
        public string Remarks { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactNo { get; set; }
        public string CustomerAddress { get; set; }
    }
}
