//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LineWDailyTargetList
    {
        public long TptId { get; set; }
        public Nullable<int> LineId { get; set; }
        public string LineName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> TQty { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
