//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ModelPartsList
    {
        public int rId { get; set; }
        public int PrModelId { get; set; }
        public int SparePartsId { get; set; }
        public decimal UnitRate { get; set; }
        public string PrModelName { get; set; }
        public string SparePartsName { get; set; }
    }
}
