//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MasterBoxDetailsV
    {
        public int AssignBoxID { get; set; }
        public string BoxBarCode { get; set; }
        public string ProductModelBarcode { get; set; }
        public string ProductName { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<System.DateTime> MfDate { get; set; }
        public string PackedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string DepotName { get; set; }
    }
}
