//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductModelList
    {
        public int PrModelId { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> WarrantyPeriodFromMf { get; set; }
        public Nullable<int> WarrantyPeriodFromSales { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
