//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PumpSelParList
    {
        public int PmpId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> ModelCode { get; set; }
        public Nullable<int> VoltId { get; set; }
        public string Volt { get; set; }
        public Nullable<int> BoringId { get; set; }
        public Nullable<decimal> SuctionSize { get; set; }
        public Nullable<int> DnId { get; set; }
        public Nullable<decimal> DNSize { get; set; }
        public Nullable<decimal> StartH { get; set; }
        public Nullable<decimal> EndH { get; set; }
        public Nullable<decimal> StartQ { get; set; }
        public Nullable<decimal> EndQ { get; set; }
        public Nullable<decimal> HP { get; set; }
        public Nullable<decimal> KW { get; set; }
        public string Image_path { get; set; }
        public string OthobaUrl { get; set; }
    }
}
