//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductDistributionHistoryV
    {
        public long RmPdId { get; set; }
        public Nullable<long> RmPmId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public string BoxBarCode { get; set; }
        public string DBarcode { get; set; }
        public string PrModelName { get; set; }
        public int ModelCode { get; set; }
        public Nullable<System.DateTime> MfDate { get; set; }
        public string PackedBy { get; set; }
        public string FromDepo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public string DealerAddress { get; set; }
        public string VehicleNumber { get; set; }
        public string ToDepoName { get; set; }
        public string Depooutsender { get; set; }
        public Nullable<System.DateTime> Depooutydate { get; set; }
    }
}
