//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PartsCost
    {
        public int ComplainNo { get; set; }
        public string CustomerName { get; set; }
        public string ProductName { get; set; }
        public string PrModelName { get; set; }
        public string SparePartsName { get; set; }
        public Nullable<int> SQty { get; set; }
        public Nullable<decimal> SRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
