//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QcHistoryDetails
    {
        public int DId { get; set; }
        public int MId { get; set; }
        public string DBarcodeNo { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> StpId { get; set; }
        public string StepsName { get; set; }
        public Nullable<int> PtsId { get; set; }
        public string PointsName { get; set; }
        public string IsProb { get; set; }
        public string QcDInfo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
    }
}
