//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RmilProdBarCode
    {
        public long RmPdId { get; set; }
        public long RmPmId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string PrModelName { get; set; }
        public int ModelCode { get; set; }
        public string DBarcode { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<System.DateTime> MfDate { get; set; }
        public Nullable<System.DateTime> MfWarDate { get; set; }
        public Nullable<System.DateTime> ServiceWarDate { get; set; }
        public Nullable<System.DateTime> AfterSalesWarrDate { get; set; }
        public Nullable<System.DateTime> AfterSalesServiceDate { get; set; }
    }
}
