//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReferenceList
    {
        public int ReferenceId { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string DeptName { get; set; }
        public string DesignationName { get; set; }
        public string CompanyName { get; set; }
    }
}
