//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RmBarProdInfo
    {
        public long RmPdId { get; set; }
        public Nullable<long> RmPmId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Wpfs { get; set; }
        public string DBarcode { get; set; }
        public Nullable<System.DateTime> MfDate { get; set; }
    }
}
