//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RptCostingWithProfitLoss
    {
        public int ComplainNo { get; set; }
        public int SerialNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public Nullable<int> SCId { get; set; }
        public string SCName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ProductName { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string ProblemName { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<decimal> PartsSubtotal { get; set; }
        public Nullable<decimal> OtherSubtotal { get; set; }
        public Nullable<decimal> DRSubtotal { get; set; }
        public Nullable<decimal> WarrentyCost { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<decimal> ProfitLossAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    }
}
