//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServiceCostPrint
    {
        public int SpCost_Id { get; set; }
        public int SerialNo { get; set; }
        public int TicketID { get; set; }
        public int ComplainNo { get; set; }
        public string ZoneName { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string PrModelName { get; set; }
        public string ProblemName { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<decimal> ReAmount { get; set; }
        public Nullable<decimal> ImAmount { get; set; }
        public Nullable<decimal> CapAmount { get; set; }
        public Nullable<decimal> ImSupportAmount { get; set; }
        public Nullable<decimal> BearingAmount { get; set; }
        public Nullable<decimal> MSealAmount { get; set; }
        public Nullable<decimal> ManPowerCost { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
    }
}
