//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServiceList1
    {
        public int Tr_Id { get; set; }
        public Nullable<int> SCId { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public int SerialNo { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public string TestReportInfo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ProblemName { get; set; }
        public string ProductName { get; set; }
        public string PrModelName { get; set; }
        public string ActionName { get; set; }
        public string StatusName { get; set; }
        public string SCName { get; set; }
        public string ZoneName { get; set; }
    }
}
