//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServicingReportNew
    {
        public int SerialNo { get; set; }
        public int TicketID { get; set; }
        public Nullable<int> TicketCode { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> SCId { get; set; }
        public string SCName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public string DillerName { get; set; }
        public string InTimeVehicleNo { get; set; }
        public string OutTimeVehicleNo { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<int> ServiceDurationTime { get; set; }
        public string ProductName { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string ProblemName { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string TestReportInfo { get; set; }
        public string Remarks { get; set; }
        public string ModelSerialNo { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> EngrStaffID { get; set; }
        public string EngineerName { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string BillNumber { get; set; }
        public string Billamount { get; set; }
        public string CancelReason { get; set; }
        public int StatusId { get; set; }
    }
}
