//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SearchFromAssign
    {
        public int TicketID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactNo { get; set; }
        public string CustomerAddress { get; set; }
        public string ProductName { get; set; }
        public string ProblemName { get; set; }
        public string StatusName { get; set; }
        public string ZoneName { get; set; }
        public string PrModelName { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string fsp { get; set; }
        public Nullable<bool> IsAssign { get; set; }
        public Nullable<bool> SendFeedback { get; set; }
        public Nullable<bool> SendGate { get; set; }
        public string SMode { get; set; }
        public string Remarks { get; set; }
    }
}
