//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServiceCostingReport
    {
        public int SpCost_Id { get; set; }
        public int SerialNo { get; set; }
        public int TicketID { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> SCId { get; set; }
        public string SCName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ProductName { get; set; }
        public int ModelCode { get; set; }
        public string PrModelName { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string ProblemName { get; set; }
        public Nullable<int> ReQty { get; set; }
        public Nullable<decimal> ReRate { get; set; }
        public Nullable<decimal> ReAmount { get; set; }
        public Nullable<int> ImQty { get; set; }
        public Nullable<decimal> ImRate { get; set; }
        public Nullable<decimal> ImAmount { get; set; }
        public Nullable<int> CapQty { get; set; }
        public Nullable<decimal> CapRate { get; set; }
        public Nullable<decimal> CapAmount { get; set; }
        public Nullable<int> ImSupportQty { get; set; }
        public Nullable<decimal> ImSupportRate { get; set; }
        public Nullable<decimal> ImSupportAmount { get; set; }
        public Nullable<int> BearingQty { get; set; }
        public Nullable<decimal> BearingRate { get; set; }
        public Nullable<decimal> BearingAmount { get; set; }
        public Nullable<int> MSealQty { get; set; }
        public Nullable<decimal> MSealRate { get; set; }
        public Nullable<decimal> MSealAmount { get; set; }
        public Nullable<decimal> BurntWireQty { get; set; }
        public Nullable<decimal> BurntWireRate { get; set; }
        public Nullable<decimal> BurntWireAmount { get; set; }
        public Nullable<decimal> BurntOilQty { get; set; }
        public Nullable<decimal> BurntOilRate { get; set; }
        public Nullable<decimal> BurntOilAmount { get; set; }
        public Nullable<decimal> ManPowerCost { get; set; }
        public Nullable<decimal> CopperWireQty { get; set; }
        public Nullable<decimal> CompressorOilQty { get; set; }
        public Nullable<int> AmpereTubeQty { get; set; }
        public Nullable<int> DRBearing { get; set; }
        public Nullable<int> DRCapacitor { get; set; }
        public Nullable<int> DRImpeller { get; set; }
        public Nullable<int> DRMSeal { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
    }
}
