//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServiceCenterStatusCount
    {
        public int SCId { get; set; }
        public string SCName { get; set; }
        public Nullable<int> TotalComplain { get; set; }
        public Nullable<int> SolvedQty { get; set; }
        public Nullable<int> UnSolvedQty { get; set; }
    }
}
