//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SparePartsCostingList
    {
        public long STrId { get; set; }
        public int ComplainNo { get; set; }
        public Nullable<int> SCId { get; set; }
        public Nullable<int> PrModelId { get; set; }
        public Nullable<int> SparePartsId { get; set; }
        public Nullable<int> SQty { get; set; }
        public Nullable<decimal> SRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
        public string PrModelName { get; set; }
        public string SparePartsName { get; set; }
    }
}
