//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SalesReturnList
    {
        public int Tr_Id { get; set; }
        public int SerialNo { get; set; }
        public int ComplainNo { get; set; }
        public string SRMode { get; set; }
        public string SRInfo { get; set; }
        public string SRNumber { get; set; }
        public string SRrejectCause { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ProblemName { get; set; }
        public string ProductName { get; set; }
        public string PrModelName { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> DillerCode { get; set; }
        public Nullable<int> SCId { get; set; }
        public string SCName { get; set; }
    }
}
