//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TempSpList
    {
        public int ComplainNo { get; set; }
        public string SP1 { get; set; }
        public string SP2 { get; set; }
        public string SP3 { get; set; }
        public string SP4 { get; set; }
        public string SP5 { get; set; }
    }
}
