//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserWiseLineList
    {
        public int RmUwLId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LineId { get; set; }
        public string LineName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
