//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserList
    {
        public int UserCode { get; set; }
        public string UserId { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string UserName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string TypeName { get; set; }
        public string CompanyName { get; set; }
        public string ZoneName { get; set; }
        public string DeptName { get; set; }
        public string DesignationName { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
