//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WarrantyInfoList
    {
        public long WrcId { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public string DealerName { get; set; }
        public string RetailerName { get; set; }
        public string CustomerName { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<System.DateTime> SalesWarDate { get; set; }
        public Nullable<System.DateTime> SalesServiceDate { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> BaseId { get; set; }
        public string BaseName { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int PrModelId { get; set; }
        public string PrModelName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Remarks { get; set; }
    }
}
