//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIL.Prod.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int ZoneId { get; set; }
        public Nullable<int> ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string EntryBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EntryPC { get; set; }
        public string ModifiedPC { get; set; }
    }
}
